# TASK:
# Implement Kubernetes manifests
---
###
# Deploymnent definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-1.0
  labels:
    app: sample-app
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
        version: "1.0"
    spec:
      containers:
      - name: pxlfrontend
        image: jozefhalgas/pxlfrontend:1.0
        ports:
        - name: sample-app-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /_nginx_status
            port: sample-app-port
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /app/test
            port: sample-app-port
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "150m"
      - name: pxlbackend
        image: jozefhalgas/pxlbackend:latest
        ports:
        - name: liveness-port
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /test
            port: liveness-port
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "150m"

---
###
# Service definition
kind: Service
apiVersion: v1
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  type: NodePort
  selector:
    app: sample-app
    version: "1.0"
  ports:
  - name: http
    port: 80
    nodePort: 31234
    protocol: TCP
    targetPort: sample-app-port

---
###
# Ingress definition
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sample-ingress
spec:
  rules:
  - host: sample-app.info
    http:
      paths:
      - backend:
          serviceName: sample-app
          servicePort: 80
---
###
# HPA definition
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sample-app
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: sample-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 15
---
###
# PDB definition
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: sample-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sample-app
      version: "1.0"
