# TASK:
# Implement Kubernetes manifests
---
###
# Deploymnent definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-1.1
  labels:
    app: sample-app
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
        version: "1.1"
    spec:
      containers:
      - name: pxlfrontend
        image: jozefhalgas/pxlfrontend:1.1
        ports:
        - name: sample-app-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /_nginx_status
            port: sample-app-port
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /app/test
            port: sample-app-port
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "150m"
      - name: pxlbackend
        image: jozefhalgas/pxlbackend:latest
        ports:
        - name: liveness-port
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /test
            port: liveness-port
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "150m"

---
# Service definition
kind: Service
apiVersion: v1
metadata:
  name: sample-app-green
  labels:
    app: sample-app
spec:
  type: NodePort
  selector:
    app: sample-app
    version: "1.1"
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: sample-app-port
